/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.anvisics.jleveldb.ext;

public final class CompressionType {
  public final static CompressionType kNoCompression = new CompressionType("kNoCompression", LeveldbJNI.kNoCompression_get());
  public final static CompressionType kSnappyCompression = new CompressionType("kSnappyCompression", LeveldbJNI.kSnappyCompression_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CompressionType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CompressionType.class + " with value " + swigValue);
  }

  private CompressionType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CompressionType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CompressionType(String swigName, CompressionType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CompressionType[] swigValues = { kNoCompression, kSnappyCompression };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

