/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.anvisics.jleveldb.ext;

public class DBAccessor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DBAccessor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DBAccessor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LeveldbJNI.delete_DBAccessor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLastStatus(Status value) {
    LeveldbJNI.DBAccessor_lastStatus_set(swigCPtr, this, Status.getCPtr(value), value);
  }

  public Status getLastStatus() {
    long cPtr = LeveldbJNI.DBAccessor_lastStatus_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Status(cPtr, false);
  }

  public Status open(Options options, String name) {
    return new Status(LeveldbJNI.DBAccessor_open(swigCPtr, this, Options.getCPtr(options), options, name), true);
  }

  public String get(ReadOptions options, String key) {
    return LeveldbJNI.DBAccessor_get(swigCPtr, this, ReadOptions.getCPtr(options), options, key);
  }

  public Status write(WriteOptions options, DBWriteBatch updates) {
    return new Status(LeveldbJNI.DBAccessor_write(swigCPtr, this, WriteOptions.getCPtr(options), options, DBWriteBatch.getCPtr(updates), updates), true);
  }

  public Status put(WriteOptions options, String key, String value) {
    return new Status(LeveldbJNI.DBAccessor_put(swigCPtr, this, WriteOptions.getCPtr(options), options, key, value), true);
  }

  public Status remove(WriteOptions options, String key) {
    return new Status(LeveldbJNI.DBAccessor_remove(swigCPtr, this, WriteOptions.getCPtr(options), options, key), true);
  }

  public DBIterator newIterator(ReadOptions options) {
    long cPtr = LeveldbJNI.DBAccessor_newIterator(swigCPtr, this, ReadOptions.getCPtr(options), options);
    return (cPtr == 0) ? null : new DBIterator(cPtr, false);
  }

  public Snapshot getSnapshot() {
    long cPtr = LeveldbJNI.DBAccessor_getSnapshot(swigCPtr, this);
    return (cPtr == 0) ? null : new Snapshot(cPtr, false);
  }

  public void releaseSnapshot(Snapshot snapshot) {
    LeveldbJNI.DBAccessor_releaseSnapshot(swigCPtr, this, Snapshot.getCPtr(snapshot), snapshot);
  }

  public String getProperty(String property) {
    return LeveldbJNI.DBAccessor_getProperty(swigCPtr, this, property);
  }

  public DBAccessor() {
    this(LeveldbJNI.new_DBAccessor(), true);
  }

}
