/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.anvisics.jleveldb.ext;

public class DBIterator {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DBIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DBIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LeveldbJNI.delete_DBIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean Valid() {
    return LeveldbJNI.DBIterator_Valid(swigCPtr, this);
  }

  public void SeekToFirst() {
    LeveldbJNI.DBIterator_SeekToFirst(swigCPtr, this);
  }

  public void SeekToLast() {
    LeveldbJNI.DBIterator_SeekToLast(swigCPtr, this);
  }

  public void Seek(String str) {
    LeveldbJNI.DBIterator_Seek(swigCPtr, this, str);
  }

  public void Next() {
    LeveldbJNI.DBIterator_Next(swigCPtr, this);
  }

  public void Prev() {
    LeveldbJNI.DBIterator_Prev(swigCPtr, this);
  }

  public String key() {
    return LeveldbJNI.DBIterator_key(swigCPtr, this);
  }

  public String value() {
    return LeveldbJNI.DBIterator_value(swigCPtr, this);
  }

  public Status status() {
    return new Status(LeveldbJNI.DBIterator_status(swigCPtr, this), true);
  }

}
