/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.anvisics.jleveldb.ext;

public class DBTableBuilder {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DBTableBuilder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DBTableBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LeveldbJNI.delete_DBTableBuilder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DBTableBuilder(Options options) {
    this(LeveldbJNI.new_DBTableBuilder(Options.getCPtr(options), options), true);
  }

  public Status setOptions(Options options) {
    return new Status(LeveldbJNI.DBTableBuilder_setOptions(swigCPtr, this, Options.getCPtr(options), options), true);
  }

  public Status getStatus() {
    return new Status(LeveldbJNI.DBTableBuilder_getStatus(swigCPtr, this), true);
  }

  public Status open(String fname) {
    return new Status(LeveldbJNI.DBTableBuilder_open(swigCPtr, this, fname), true);
  }

  public Status add(String key, String value) {
    return new Status(LeveldbJNI.DBTableBuilder_add(swigCPtr, this, key, value), true);
  }

  public void flush() {
    LeveldbJNI.DBTableBuilder_flush(swigCPtr, this);
  }

  public long numEntries() {
    return LeveldbJNI.DBTableBuilder_numEntries(swigCPtr, this);
  }

  public long fileSize() {
    return LeveldbJNI.DBTableBuilder_fileSize(swigCPtr, this);
  }

  public Status finish() {
    return new Status(LeveldbJNI.DBTableBuilder_finish(swigCPtr, this), true);
  }

  public void abandon() {
    LeveldbJNI.DBTableBuilder_abandon(swigCPtr, this);
  }

}
