/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.anvisics.jleveldb.ext;

public class DBTable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DBTable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DBTable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LeveldbJNI.delete_DBTable(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static DBTable open(Options options, String filename, long fileSize) {
    long cPtr = LeveldbJNI.DBTable_open(Options.getCPtr(options), options, filename, fileSize);
    return (cPtr == 0) ? null : new DBTable(cPtr, false);
  }

  public DBIterator newIterator(ReadOptions opts) {
    long cPtr = LeveldbJNI.DBTable_newIterator(swigCPtr, this, ReadOptions.getCPtr(opts), opts);
    return (cPtr == 0) ? null : new DBIterator(cPtr, false);
  }

  public long approximateOffsetOf(String key) {
    return LeveldbJNI.DBTable_approximateOffsetOf(swigCPtr, this, key);
  }

}
