/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.anvisics.jleveldb.ext;

public class DBWriteBatch {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DBWriteBatch(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DBWriteBatch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LeveldbJNI.delete_DBWriteBatch(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setWb(WriteBatch value) {
    LeveldbJNI.DBWriteBatch_wb_set(swigCPtr, this, WriteBatch.getCPtr(value), value);
  }

  public WriteBatch getWb() {
    long cPtr = LeveldbJNI.DBWriteBatch_wb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new WriteBatch(cPtr, false);
  }

  public void Put(String key, String value) {
    LeveldbJNI.DBWriteBatch_Put(swigCPtr, this, key, value);
  }

  public void Delete(String key) {
    LeveldbJNI.DBWriteBatch_Delete(swigCPtr, this, key);
  }

  public void Clear() {
    LeveldbJNI.DBWriteBatch_Clear(swigCPtr, this);
  }

  public DBWriteBatch() {
    this(LeveldbJNI.new_DBWriteBatch(), true);
  }

}
