/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.anvisics.jleveldb.ext;

public class Leveldb {
  public static Status DestroyDB(String name, Options options) {
    return new Status(LeveldbJNI.DestroyDB(name, Options.getCPtr(options), options), true);
  }

  public static Status RepairDB(String dbname, Options options) {
    return new Status(LeveldbJNI.RepairDB(dbname, Options.getCPtr(options), options), true);
  }

  public static Snapshot getSnapshotValue(SWIGTYPE_p_p_leveldb__Snapshot p) {
    long cPtr = LeveldbJNI.getSnapshotValue(SWIGTYPE_p_p_leveldb__Snapshot.getCPtr(p));
    return (cPtr == 0) ? null : new Snapshot(cPtr, false);
  }

}
