/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.anvisics.jleveldb.ext;

public class Options {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Options(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Options obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LeveldbJNI.delete_Options(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Options() {
    this(LeveldbJNI.new_Options(), true);
  }

  public void setCreateIfMissing(boolean value) {
    LeveldbJNI.Options_createIfMissing_set(swigCPtr, this, value);
  }

  public boolean getCreateIfMissing() {
    return LeveldbJNI.Options_createIfMissing_get(swigCPtr, this);
  }

  public void setErrorIfExists(boolean value) {
    LeveldbJNI.Options_errorIfExists_set(swigCPtr, this, value);
  }

  public boolean getErrorIfExists() {
    return LeveldbJNI.Options_errorIfExists_get(swigCPtr, this);
  }

  public void setParanoidChecks(boolean value) {
    LeveldbJNI.Options_paranoidChecks_set(swigCPtr, this, value);
  }

  public boolean getParanoidChecks() {
    return LeveldbJNI.Options_paranoidChecks_get(swigCPtr, this);
  }

  public void setWriteBufferSize(long value) {
    LeveldbJNI.Options_writeBufferSize_set(swigCPtr, this, value);
  }

  public long getWriteBufferSize() {
    return LeveldbJNI.Options_writeBufferSize_get(swigCPtr, this);
  }

  public void setMaxOpenFiles(int value) {
    LeveldbJNI.Options_maxOpenFiles_set(swigCPtr, this, value);
  }

  public int getMaxOpenFiles() {
    return LeveldbJNI.Options_maxOpenFiles_get(swigCPtr, this);
  }

  public void setBlockSize(long value) {
    LeveldbJNI.Options_blockSize_set(swigCPtr, this, value);
  }

  public long getBlockSize() {
    return LeveldbJNI.Options_blockSize_get(swigCPtr, this);
  }

  public void setBlockRestartInterval(int value) {
    LeveldbJNI.Options_blockRestartInterval_set(swigCPtr, this, value);
  }

  public int getBlockRestartInterval() {
    return LeveldbJNI.Options_blockRestartInterval_get(swigCPtr, this);
  }

  public void setCompression(CompressionType value) {
    LeveldbJNI.Options_compression_set(swigCPtr, this, value.swigValue());
  }

  public CompressionType getCompression() {
    return CompressionType.swigToEnum(LeveldbJNI.Options_compression_get(swigCPtr, this));
  }

}
