/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.anvisics.jleveldb.ext;

public class Options {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Options(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Options obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LeveldbJNI.delete_Options(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Options() {
    this(LeveldbJNI.new_Options(), true);
  }

  public void setCreate_if_missing(boolean value) {
    LeveldbJNI.Options_create_if_missing_set(swigCPtr, this, value);
  }

  public boolean getCreate_if_missing() {
    return LeveldbJNI.Options_create_if_missing_get(swigCPtr, this);
  }

  public void setError_if_exists(boolean value) {
    LeveldbJNI.Options_error_if_exists_set(swigCPtr, this, value);
  }

  public boolean getError_if_exists() {
    return LeveldbJNI.Options_error_if_exists_get(swigCPtr, this);
  }

  public void setParanoid_checks(boolean value) {
    LeveldbJNI.Options_paranoid_checks_set(swigCPtr, this, value);
  }

  public boolean getParanoid_checks() {
    return LeveldbJNI.Options_paranoid_checks_get(swigCPtr, this);
  }

  public void setWrite_buffer_size(long value) {
    LeveldbJNI.Options_write_buffer_size_set(swigCPtr, this, value);
  }

  public long getWrite_buffer_size() {
    return LeveldbJNI.Options_write_buffer_size_get(swigCPtr, this);
  }

  public void setMax_open_files(int value) {
    LeveldbJNI.Options_max_open_files_set(swigCPtr, this, value);
  }

  public int getMax_open_files() {
    return LeveldbJNI.Options_max_open_files_get(swigCPtr, this);
  }

  public void setBlock_size(long value) {
    LeveldbJNI.Options_block_size_set(swigCPtr, this, value);
  }

  public long getBlock_size() {
    return LeveldbJNI.Options_block_size_get(swigCPtr, this);
  }

  public void setBlock_restart_interval(int value) {
    LeveldbJNI.Options_block_restart_interval_set(swigCPtr, this, value);
  }

  public int getBlock_restart_interval() {
    return LeveldbJNI.Options_block_restart_interval_get(swigCPtr, this);
  }

  public void setCompression(CompressionType value) {
    LeveldbJNI.Options_compression_set(swigCPtr, this, value.swigValue());
  }

  public CompressionType getCompression() {
    return CompressionType.swigToEnum(LeveldbJNI.Options_compression_get(swigCPtr, this));
  }

}
