/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.anvisics.jleveldb.ext;

public class ReadOptions {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ReadOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ReadOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LeveldbJNI.delete_ReadOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVerify_checksums(boolean value) {
    LeveldbJNI.ReadOptions_verify_checksums_set(swigCPtr, this, value);
  }

  public boolean getVerify_checksums() {
    return LeveldbJNI.ReadOptions_verify_checksums_get(swigCPtr, this);
  }

  public void setFill_cache(boolean value) {
    LeveldbJNI.ReadOptions_fill_cache_set(swigCPtr, this, value);
  }

  public boolean getFill_cache() {
    return LeveldbJNI.ReadOptions_fill_cache_get(swigCPtr, this);
  }

  public ReadOptions() {
    this(LeveldbJNI.new_ReadOptions(), true);
  }

}
