/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.anvisics.jleveldb.ext;

public class ReadOptions {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ReadOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ReadOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LeveldbJNI.delete_ReadOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVerifyChecksums(boolean value) {
    LeveldbJNI.ReadOptions_verifyChecksums_set(swigCPtr, this, value);
  }

  public boolean getVerifyChecksums() {
    return LeveldbJNI.ReadOptions_verifyChecksums_get(swigCPtr, this);
  }

  public void setFillCache(boolean value) {
    LeveldbJNI.ReadOptions_fillCache_set(swigCPtr, this, value);
  }

  public boolean getFillCache() {
    return LeveldbJNI.ReadOptions_fillCache_get(swigCPtr, this);
  }

  public void setSnapshot(Snapshot value) {
    LeveldbJNI.ReadOptions_snapshot_set(swigCPtr, this, Snapshot.getCPtr(value), value);
  }

  public Snapshot getSnapshot() {
    long cPtr = LeveldbJNI.ReadOptions_snapshot_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Snapshot(cPtr, false);
  }

  public ReadOptions() {
    this(LeveldbJNI.new_ReadOptions(), true);
  }

}
