/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.anvisics.jleveldb.ext;

public class Status {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Status(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Status obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LeveldbJNI.delete_Status(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean ok() {
    return LeveldbJNI.Status_ok(swigCPtr, this);
  }

  public boolean IsNotFound() {
    return LeveldbJNI.Status_IsNotFound(swigCPtr, this);
  }

  public String ToString() {
    return LeveldbJNI.Status_ToString(swigCPtr, this);
  }

  public Status() {
    this(LeveldbJNI.new_Status(), true);
  }

}
