/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.anvisics.jleveldb.ext;

public class WriteOptions {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected WriteOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WriteOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LeveldbJNI.delete_WriteOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public WriteOptions() {
    this(LeveldbJNI.new_WriteOptions(), true);
  }

  public void setSync(boolean value) {
    LeveldbJNI.WriteOptions_sync_set(swigCPtr, this, value);
  }

  public boolean getSync() {
    return LeveldbJNI.WriteOptions_sync_get(swigCPtr, this);
  }

}
